### PR TITLE
Sprint 3 - Allow employers to view job postings they made

### PR DESCRIPTION
**Pull request by emeka-okechukwu**
Hi team,

Worked with @Abdel1107 to solve the issues #36 and #37 which both creates a job postings page and displays the jobs the employers made.

Please review and let me know what you think.

PS: Use dummy data from Django administrator end to test the feature

### CODE REVIEW

**Review by Rubello21 — APPROVED** [review]
I like the way it looks, it is working well on my end.

**Review by kadiralt — APPROVED** [review]
I reviewed the codes and they look good.

**Review by j3rrimmy — APPROVED** [review]
I checked the changes and I approve, it's all good.

**Review by L3CH3R0 — APPROVED** [review]
Ran the server on my end with dummy data and it works....closing the PR and merging it

**Pull request merged**
