### PR TITLE
Sprint 3 - Allow employers to add their job postings to the database

### PR DESCRIPTION
**Pull request by Rubello21**
Hi, Abdel and I have done #38 and #39 . Please check and lemme know what you think

### CODE REVIEW

**Review by emeka-okechukwu — COMMENTED** [review]
It runs nicely on my system. @Rubello21, can we look into adding test cases that involve adding a new job posting?

**Comment by Rubello21** [comment]
@emeka-okechukwu-dev I have added it and it should run when you merge it to the main branch

**Review by emeka-okechukwu — APPROVED** [review]
Alright, I have noted the changes and approved

**Review by kadiralt — APPROVED** [review]
Yeah looks good for me as well...merging it now

**Pull request merged**
